export const categoriasFiguras = [
    { nombre: "Animales", items: ['icofont-dog-alt', 'icofont-cat-alt-2', 'icofont-rabbit', 'icofont-fox', 'icofont-bear-face', 'icofont-panda', 'icofont-rhino-head', 'icofont-lion-head', 'icofont-tiger-face', 'icofont-cow-head'] },
    { nombre: "Animals", items: ['icofont-rat', 'icofont-snake', 'icofont-pig', 'icofont-panther', 'icofont-lemur', 'icofont-frog', 'icofont-bat', 'icofont-deer-head', 'icofont-elk', 'icofont-giraffe-head-2'] },
    { nombre: "Frutas", items: ['icofont-apple', 'icofont-banana', 'icofont-watermelon', 'icofont-grapes', 'icofont-strawberry', 'icofont-pineapple', 'icofont-kiwi', 'icofont-mango', 'icofont-cherry', 'icofont-lemon-alt'] },
    { nombre: "Fruts", items: ['icofont-avocado', 'icofont-coconut', 'icofont-corn', 'icofont-fruits', 'icofont-wheat', 'icofont-lemon', 'icofont-honey', 'icofont-cucumber', 'icofont-pear', 'icofont-orange'] },
    { nombre: "Deportes", items: ['icofont-football', 'icofont-basketball', 'icofont-football-american', 'icofont-golf-alt', 'icofont-table-tennis', 'icofont-volleyball', 'icofont-bowling', 'icofont-badminton-birdie', 'icofont-rugby', 'icofont-tennis'] },
    { nombre: "Sport", items: ['icofont-swimmer', 'icofont-steering', 'icofont-padding', 'icofont-hockey', 'icofont-baseballer', 'icofont-racer', 'icofont-skiing-man', 'icofont-runner-alt-1', 'icofont-tracking', 'icofont-climbing'] },
    { nombre: "Comida", items: ['icofont-pizza-slice', 'icofont-burger', 'icofont-french-fries', 'icofont-hot-dog', 'icofont-cheese', 'icofont-bread', 'icofont-chicken-fry', 'icofont-sandwich', 'icofont-taco', 'icofont-croissant'] },
    { nombre: "Vehículos", items: ['icofont-car', 'icofont-car-alt-3', 'icofont-auto-rickshaw', 'icofont-bus-alt-1', 'icofont-truck-alt', 'icofont-truck', 'icofont-taxi', 'icofont-fast-delivery', 'icofont-fire-truck', 'icofont-tractor'] },
    { nombre: "Divisas", items: ['icofont-dollar', 'icofont-euro', 'icofont-peseta', 'icofont-lira', 'icofont-hryvnia', 'icofont-frank', 'icofont-dong', 'icofont-bitcoin', 'icofont-afghani', 'Bs.'] },
    { nombre: "Monedas", items: ['icofont-won', 'icofont-yen', 'icofont-turkish-lira', 'icofont-taka', 'icofont-rupee', 'icofont-rouble', 'icofont-pound', 'icofont-riyal', 'icofont-renminbi', 'icofont-peso'] },
    { nombre: "Pagos", items: ['icofont-western-union', 'icofont-visa-electron', 'icofont-jcb', 'icofont-eway', 'icofont-discover', 'icofont-cash-on-delivery', 'icofont-braintree', 'icofont-bank-transfer', 'icofont-amazon-alt', 'icofont-2checkout'] },
    { nombre: "Payment", items: ['icofont-apple-pay', 'icofont-visa', 'icofont-diners-club', 'icofont-stripe', 'icofont-mastercard', 'icofont-paypal', 'icofont-maestro', 'icofont-payoneer', 'icofont-google-wallet', 'icofont-sage'] },
    { nombre: "Caritas", items: ['icofont-angry', 'icofont-astonished', 'icofont-simple-smile', 'icofont-confused', 'icofont-crying', 'icofont-nerd-smile', 'icofont-expressionless', 'icofont-heart-eyes', 'icofont-laughing', 'icofont-dizzy'] },
    { nombre: "Emoji", items: ['icofont-open-mouth', 'icofont-rage', 'icofont-rolling-eyes', 'icofont-sad', 'icofont-confounded', 'icofont-stuck-out-tongue', 'icofont-smirk', 'icofont-slightly-smile', 'icofont-worried', 'icofont-wink-smile'] },
    { nombre: "Construcción", items: ['icofont-architecture-alt', 'icofont-architecture', 'icofont-barricade', 'icofont-worker', 'icofont-bricks', 'icofont-bolt', 'icofont-cement-mix', 'icofont-calculations', 'icofont-workers-group', 'icofont-danger-zone'] },
    { nombre: "Construction", items: ['icofont-help-robot', 'icofont-cement-mixer', 'icofont-eco-environmen', 'icofont-eco-energy', 'icofont-energy-savings', 'icofont-energy-oil', 'icofont-energy-air', 'icofont-energy-water', 'icofont-energy-solar', 'icofont-radio-active'] },
    { nombre: "Tools", items: ['icofont-drill', 'icofont-fix-tools', 'icofont-hammer', 'icofont-wrench', 'icofont-calculations', 'icofont-paint-brush', 'icofont-screw-driver', 'icofont-saw', 'icofont-trolley', 'icofont-trowel'] },
    { nombre: "Herramientas", items: ['icofont-fire-extinguisher-alt', 'icofont-glue-oil', 'icofont-power-zone', 'icofont-recycle-alt', 'icofont-recycling-man', 'icofont-safety-hat-light', 'icofont-tools-1', 'icofont-tools-bag', 'icofont-under-construction-alt', 'icofont-labour'] },
    { nombre: "Industria", items: ['icofont-mining', 'icofont-pollution', 'icofont-industries', 'icofont-industries-3', 'icofont-industries-1', 'icofont-industries-2', 'icofont-industries-4', 'icofont-industries-5', 'icofont-industries', 'icofont-building-alt'] },
    { nombre: "Maquinaria", items: ['icofont-vehicle-wrecking', 'icofont-vehicle-trucktor', 'icofont-vehicle-excavator', 'icofont-vehicle-dozer', 'icofont-vehicle-delivery-van', 'icofont-vehicle-crane', 'icofont-vehicle-cement', 'icofont-tow-truck', 'icofont-concrete-mixer', 'icofont-fork-lift'] },
    { nombre: "Naturaleza", items: ['icofont-eclipse', 'icofont-forest-fire', 'icofont-night', 'icofont-sun-alt', 'icofont-thunder-light', 'icofont-snow', 'icofont-volcano', 'icofont-clouds', 'icofont-tornado', 'icofont-wave'] },
    { nombre: "Clima", items: ['icofont-sunny-day-temp', 'icofont-wind', 'icofont-sunny', 'icofont-rainy', 'icofont-celsius', 'icofont-fahrenheit', 'icofont-breakdown', 'icofont-rainy-thunder', 'icofont-sun-set', 'icofont-umbrella'] },
    { nombre: "Negocio", items: ['icofont-bank', 'icofont-barcode', 'icofont-briefcase-1', 'icofont-bill-alt', 'icofont-coins', 'icofont-stamp', 'icofont-files-stack', 'icofont-handshake-deal', 'icofont-money-bag', 'icofont-presentation'] },
    { nombre: "Kids", items: ['icofont-baby-milk-bottle', 'icofont-candy', 'icofont-baby', 'icofont-baby-cloth', 'icofont-baby-trolley', 'icofont-toy-horse', 'icofont-toy-lattu', 'icofont-safety-pin', 'icofont-toy-hand', 'icofont-baby-backpack'] },
    { nombre: "Bebidas", items: ['icofont-soft-drinks', 'icofont-coffee-mug', 'icofont-cola', 'icofont-juice', 'icofont-cocktail', 'icofont-beer', 'icofont-milk', 'icofont-tea-pot', 'icofont-coconut-water', 'icofont-coffee-alt'] },
    { nombre: "Interfaz", items: ['icofont-ui-bluetooth', 'icofont-ui-alarm', 'icofont-ui-calendar', 'icofont-ui-camera', 'icofont-ui-clip', 'icofont-ui-video-play', 'icofont-ui-password', 'icofont-ui-music', 'icofont-ui-network', 'icofont-ui-touch-phone'] },
    { nombre: "Interfaz 2", items: ['icofont-ui-game', 'icofont-ui-email', 'icofont-ui-music-player', 'icofont-ui-power', 'icofont-ui-settings', 'icofont-ui-social-link', 'icofont-eraser', 'icofont-ui-search', 'icofont-ui-message', 'icofont-ui-edit'] },
    { nombre: "Buscar", items: ['icofont-search-job', 'icofont-search-folder', 'icofont-search-document', 'icofont-search-property', 'icofont-search-restaurant', 'icofont-search-stock', 'icofont-search-user', 'icofont-search-map', 'icofont-search-2', 'icofont-search-1'] },
    { nombre: "Viajar", items: ['icofont-air-ticket', 'icofont-direction-sign', 'icofont-island-alt', 'icofont-beach', 'icofont-5-star-hotel', 'icofont-camping-vest', 'icofont-hotel', 'icofont-island', 'icofont-sandals-female', 'icofont-sandals-male'] },
    { nombre: "Gym", items: ['icofont-gym-alt-2', 'icofont-muscle-weight', 'icofont-dumbbell', 'icofont-cycling', 'icofont-gym-alt-1', 'icofont-gym', 'icofont-gym-alt-3', 'icofont-dumbbells', 'icofont-cycling-alt', 'icofont-muscle'] },
    { nombre: "Chart", items: ['icofont-chart-flow-2', 'icofont-chart-histogram', 'icofont-chart-flow-1', 'icofont-chart-arrows-axis', 'icofont-chart-flow', 'icofont-chart-pie', 'icofont-chart-line', 'icofont-chart-pie-alt', 'icofont-chart-line-alt', 'icofont-chart-bar-graph'] },
    { nombre: "Aves", items: ['icofont-eagle-head', 'icofont-toy-duck', 'icofont-penguin', 'icofont-rooster', 'icofont-woodpecker', 'icofont-bird-alt', 'icofont-owl', 'icofont-pelican', 'icofont-pigeon-2', 'icofont-parrot'] },
    { nombre: "Education", items: ['icofont-abc', 'icofont-book-alt', 'icofont-globe-alt', 'icofont-instrument', 'icofont-pencil-alt-5', 'icofont-test-tube-alt', 'icofont-microscope-alt', 'icofont-certificate-alt-1', 'icofont-hat', 'icofont-paper'] },
    { nombre: "Educación", items: ['icofont-medal', 'icofont-lamp-light', 'icofont-school-bag', 'icofont-read-book', 'icofont-test-bulb', 'icofont-university', 'icofont-brainstorming', 'icofont-certificate-alt-2', 'icofont-black-board', 'icofont-graduate-alt'] },
    { nombre: "Multimedia", items: ['icofont-music-disk', 'icofont-volume-up', 'icofont-multimedia', 'icofont-record', 'icofont-cassette-player', 'icofont-video-alt', 'icofont-video-clapper', 'icofont-cassette', 'icofont-volume-mute', 'icofont-video-cam'] },
    { nombre: "Thing", items: ['icofont-anchor', 'icofont-binoculars', 'icofont-bomb', 'icofont-box', 'icofont-bucket', 'icofont-bullseye', 'icofont-cart-alt', 'icofont-code', 'icofont-dice', 'icofont-diskette'] },
    { nombre: "Others", items: ['icofont-home', 'icofont-hour-glass', 'icofont-karate', 'icofont-jewlery', 'icofont-letter', 'icofont-life-buoy', 'icofont-lighter', 'icofont-megaphone', 'icofont-mop', 'icofont-print'] },
    { nombre: "Cosas", items: ['icofont-news', 'icofont-newspaper', 'icofont-telescope', 'icofont-space', 'icofont-paint', 'icofont-plugin', 'icofont-puzzle', 'icofont-usb-drive', 'icofont-royal', 'icofont-recycle'] },
    { nombre: "Mamíferos", items: ['icofont-zebra', 'icofont-gorilla', 'icofont-horse-head-2', 'icofont-giraffe', 'icofont-squirrel', 'icofont-camel', 'icofont-monkey-3', 'icofont-kangaroo', 'icofont-bull', 'icofont-elephant-head'] },
    { nombre: "Acuaticos", items: ['icofont-fish', 'icofont-crocodile', 'icofont-dolphin', 'icofont-crab', 'icofont-turtle', 'icofont-octopus', 'icofont-seahorse', 'icofont-shrimp-alt', 'icofont-whale', 'icofont-seal'] },
    { nombre: "Transporte", items: ['icofont-air-balloon', 'icofont-airplane-alt', 'icofont-bicycle', 'icofont-helicopter', 'icofont-rocket-alt-2', 'icofont-motor-biker', 'icofont-sail-boat', 'icofont-train-steam', 'icofont-ship-alt', 'icofont-cable-car'] },
    { nombre: "Vegetables", items: ['icofont-egg-plant', 'icofont-bell-pepper-capsicum', 'icofont-broccoli', 'icofont-pumpkin', 'icofont-mushroom', 'icofont-onion', 'icofont-potato', 'icofont-carrot', 'icofont-pepper', 'icofont-tomato'] },
    { nombre: "Profesión", items: ['icofont-farmer-alt', 'icofont-police', 'icofont-lawyer', 'icofont-legal', 'icofont-nurse-alt', 'icofont-doctor', 'icofont-labour', 'icofont-military', 'icofont-investigator', 'icofont-burglar'] },
    { nombre: "Ley", items: ['icofont-law-order', 'icofont-handcuff', 'icofont-law-alt-1', 'icofont-pistol', 'icofont-thief-alt', 'icofont-jail', 'icofont-cop-badge', 'icofont-lawyer-alt-2', 'icofont-law-scales', 'icofont-law-document'] },
    { nombre: "Persona", items: ['icofont-boy', 'icofont-business-man', 'icofont-girl-alt', 'icofont-kid', 'icofont-woman-in-glasses', 'icofont-hotel-boy-alt', 'icofont-funky-man', 'icofont-girl', 'icofont-man-in-glasses', 'icofont-waiter'] },
    { nombre: "Person", items: ['icofont-support', 'icofont-user-alt-5', 'icofont-user-female', 'icofont-user-suited', 'icofont-users-alt-4', 'icofont-users-alt-6', 'icofont-users-social', 'icofont-users-alt-2', 'icofont-users-alt-1', 'icofont-group'] },
    { nombre: "Marcas", items: ['icofont-brand-cnn', 'icofont-brand-apple', 'icofont-brand-amazon', 'icofont-brand-dell', 'icofont-brand-playstation', 'icofont-brand-netflix', 'icofont-brand-android-robot', 'icofont-brand-shell', 'icofont-brand-general-electric', 'icofont-brand-nasa'] },
    { nombre: "Brand", items: ['icofont-brand-adidas', 'icofont-brand-blackberry', 'icofont-brand-puma', 'icofont-brand-casio', 'icofont-brand-java', 'icofont-brand-gillette', 'icofont-brand-hp', 'icofont-brand-lg', 'icofont-brand-warnerbros', 'icofont-brand-motorola'] },
    { nombre: "Logos", items: ['icofont-brand-levis', 'icofont-brand-lego', 'icofont-brand-intel', 'icofont-brand-ikea', 'icofont-brand-linux', 'icofont-brand-nike', 'icofont-brand-mytv', 'icofont-brand-wikipedia', 'icofont-brand-samsung', 'icofont-brand-java'] },
    { nombre: "Marca de comida", items: ['icofont-brand-nescafe', 'icofont-brand-redbull', 'icofont-brand-mcdonals', 'icofont-brand-cocal-cola', 'icofont-brand-nestle', 'icofont-brand-burger-king', 'icofont-brand-pizza-hut', 'icofont-brand-eleven', 'icofont-brand-pepsi', 'icofont-brand-starbucks'] },
    { nombre: "RRSS", items: ['icofont-facebook', 'icofont-linkedin', 'icofont-tiktok', 'icofont-tinder', 'icofont-instagram', 'icofont-youtube', 'icofont-telegram', 'icofont-wechat', 'icofont-pinterest', 'icofont-whatsapp'] },
    { nombre: "RRSS 2", items: ['icofont-facebook-messenger', 'icofont-spotify', 'icofont-twitch', 'icofont-x', 'icofont-soundcloud', 'icofont-reddit', 'icofont-rss', 'icofont-discord', 'icofont-bbm-messenger', 'icofont-blogger'] },
       { nombre: "RRSS 3", items: ['icofont-badoo', 'icofont-dropbox', 'icofont-google-hangouts', 'icofont-google-plus', 'icofont-line-messenger', 'icofont-live-messenger', 'icofont-shopify', 'icofont-trello', 'icofont-yahoo', 'icofont-ubercart'] },
           { nombre: "Medicina", items: ['icofont-ambulance', 'icofont-bandage', 'icofont-capsule', 'icofont-heart-beat', 'icofont-drug', 'icofont-first-aid', 'icofont-stethoscope-alt', 'icofont-hospital', 'icofont-injection-syringe', 'icofont-medicine'] },
    { nombre: "Medicina 2", items: ['icofont-nurse', 'icofont-pills', 'icofont-pulse', 'icofont-stethoscope', 'icofont-surgeon', 'icofont-thermometer', 'icofont-tooth', 'icofont-heart-alt', 'icofont-microscope', 'icofont-test-tube'] },
    { nombre: "Salud", items: ['icofont-xray', 'icofont-medical-sign-alt', 'icofont-crutch', 'icofont-wheelchair', 'icofont-prescription', 'icofont-dna', 'icofont-blood-drop', 'icofont-bone', 'icofont-brain', 'icofont-blood'] },

        { nombre: "Interfaz 3", items: ['icofont-ui-add', 'icofont-ui-laoding', 'icofont-ui-alarm', 'icofont-ui-battery', 'icofont-ui-block', 'icofont-ui-bluetooth', 'icofont-ui-brightness', 'icofont-ui-browser', 'icofont-ui-calculator', 'icofont-ui-calendar'] },

    { nombre: "Interfaz 4", items: ['icofont-ui-call', 'icofont-ui-camera', 'icofont-ui-cart', 'icofont-ui-cell-phone', 'icofont-ui-chat', 'icofont-ui-check', 'icofont-ui-clip', 'icofont-ui-close', 'icofont-ui-map', 'icofont-ui-settings'] },
    { nombre: "Interfaz 5", items: ['icofont-ui-contact-list', 'icofont-ui-copy', 'icofont-ui-cut', 'icofont-ui-delete', 'icofont-ui-dial-phone', 'icofont-ui-image', 'icofont-ui-edit', 'icofont-ui-email', 'icofont-ui-file', 'icofont-ui-folder'] },
        { nombre: "Brand 2", items: ['icofont-brand-adobe', 'icofont-brand-airbnb', 'icofont-brand-android', 'icofont-brand-alibaba', 'icofont-brand-bbc', 'icofont-brand-asus', 'icofont-brand-bing', 'icofont-brand-unilever', 'icofont-brand-aliexpress', 'icofont-brand-att'] },
    { nombre: "Brand 3", items: ['icofont-brand-toshiba', 'icofont-brand-box', 'icofont-brand-dodge', 'icofont-brand-cnet', 'icofont-brand-compaq', 'icofont-brand-citibank', 'icofont-brand-china-mobile', 'icofont-brand-cannon', 'icofont-brand-cisco', 'icofont-brand-foursquare'] },
    { nombre: "Brand 4", items: ['icofont-brand-disney', 'icofont-brand-emirates', 'icofont-brand-espn', 'icofont-brand-hsbc', 'icofont-brand-fedex', 'icofont-brand-forbes', 'icofont-brand-hallmark', 'icofont-brand-ibm', 'icofont-brand-huawei', 'icofont-brand-hulu'] },
{ nombre: "Marcas de Carros", items: ['icofont-brand-gucci', 'icofont-brand-honda', 'icofont-brand-hyundai', 'icofont-brand-mercedes', 'icofont-brand-ferrari', 'icofont-brand-tesla', 'icofont-brand-toyota', 'icofont-brand-volkswagen', 'icofont-brand-audi', 'icofont-brand-bmw'] },
        { nombre: "Dispositivos", items: ['icofont-playstation-alt', 'icofont-radio', 'icofont-washing-machine', 'icofont-refrigerator', 'icofont-wifi-router', 'icofont-mp3-player', 'icofont-xbox-360', 'icofont-wireless-mouse', 'icofont-ui-head-phone', 'icofont-ui-keyboard'] },
    { nombre: "Dispositivos 2", items: ['icofont-game-console', 'icofont-fax', 'icofont-hard-disk', 'icofont-server', 'icofont-radio-mic', 'icofont-nintendo', 'icofont-micro-chip', 'icofont-ipod-nano', 'icofont-microphone-alt', 'icofont-headphone'] },
  
    { nombre: "Abstract", items: ['icofont-angry-monster', 'icofont-bathtub', 'icofont-bird-wings', 'icofont-bow', 'icofont-castle', 'icofont-circuit', 'icofont-crown-king', 'icofont-crown-queen', 'icofont-dart', 'icofont-disability-race'] },

    { nombre: "Abstract 2", items: ['icofont-diving-goggle', 'icofont-eye-open', 'icofont-flora-flower', 'icofont-flora', 'icofont-gift-box', 'icofont-halloween-pumpkin', 'icofont-hand-power', 'icofont-hand-thunder', 'icofont-king-monster', 'icofont-love'] },

  { nombre: "Abstract 3", items: ['icofont-magician-hat', 'icofont-native-american', 'icofont-owl-look', 'icofont-phoenix', 'icofont-robot-face', 'icofont-sand-clock', 'icofont-shield-alt', 'icofont-ship-wheel', 'icofont-skull-danger', 'icofont-snowmobile'] },

{ nombre: "Abstract 4", items: ['icofont-star-shape', 'icofont-swirl', 'icofont-tattoo-wing', 'icofont-throne', 'icofont-tree-alt', 'icofont-triangle', 'icofont-unity-hand', 'icofont-woman-bird', 'icofont-weed', 'icofont-skull-face'] },

        { nombre: "Directional", items: ['icofont-arrow-up', 'icofont-arrow-right', 'icofont-arrow-down', 'icofont-arrow-left', 'icofont-caret-up', 'icofont-caret-right', 'icofont-caret-down', 'icofont-caret-left', 'icofont-rounded-up', 'icofont-rounded-right'] },

    { nombre: "Directional 2", items: ['icofont-rounded-down', 'icofont-rounded-left', 'icofont-hand-drawn-up', 'icofont-hand-drawn-right', 'icofont-hand-drawn-down', 'icofont-hand-drawn-left', 'icofont-long-arrow-up', 'icofont-long-arrow-right', 'icofont-long-arrow-down', 'icofont-long-arrow-left'] },

    { nombre: "Directional 3", items: ['icofont-block-right', 'icofont-block-left', 'icofont-cursor-drag', 'icofont-hand-grippers', 'icofont-swoosh-up', 'icofont-swoosh-right', 'icofont-swoosh-down', 'icofont-swoosh-left', 'icofont-block-up', 'icofont-block-down'] },

 { nombre: "Directional 4", items: ['icofont-circled-left', 'icofont-circled-right', 'icofont-dotted-down', 'icofont-dotted-up', 'icofont-dotted-left', 'icofont-dotted-right', 'icofont-circled-down', 'icofont-circled-up', 'icofont-expand-alt', 'icofont-collapse'] },

{ nombre: "Directional 5", items: ['icofont-bubble-down', 'icofont-bubble-right', 'icofont-bubble-up', 'icofont-bubble-left', 'icofont-hand-down', 'icofont-hand-up', 'icofont-hand-right', 'icofont-hand-left', 'icofont-hand-drag1', 'icofont-hand-drag2'] },

{ nombre: "Directional 6", items: ['icofont-simple-left-down', 'icofont-simple-left-up', 'icofont-simple-right-down', 'icofont-simple-right-up', 'icofont-stylish-down', 'icofont-stylish-left', 'icofont-stylish-right', 'icofont-stylish-up', 'icofont-hand-drag', 'icofont-thin-up'] },

        { nombre: "Archivos", items: ['icofont-file-code', 'icofont-file-css', 'icofont-file-python', 'icofont-file-ruby', 'icofont-file-sql', 'icofont-file-java', 'icofont-file-php', 'icofont-file-javascript', 'icofont-file-html5', 'icofont-file-iso'] },

    { nombre: "Archivos 2", items: ['icofont-file-word', 'icofont-file-text', 'icofont-file-spreadsheet', 'icofont-file-pdf', 'icofont-file-presentation', 'icofont-file-gif', 'icofont-file-jpg', 'icofont-file-zip', 'icofont-file-midi', 'icofont-file-video'] },

    { nombre: "Archivos 3", items: ['icofont-file-wave', 'icofont-file-tiff', 'icofont-file-psd', 'icofont-file-png', 'icofont-file-powerpoint', 'icofont-file-mov', 'icofont-file-exe', 'icofont-file-excel', 'icofont-file-bmp', 'icofont-file-document'] },

 { nombre: "Archivos 4", items: ['icofont-file-alt', 'icofont-file-audio', 'icofont-file-avi-mp4', 'icofont-file-flv', 'icofont-file-image', 'icofont-file-file', 'icofont-file-mp3', 'icofont-file-psb', 'icofont-file-svg', 'icofont-file-eps'] },

        { nombre: "Matemáticas", items: ['icofont-angle-180', 'icofont-square-root', 'icofont-abacus', 'icofont-angle-45', 'icofont-ui-calculator', 'icofont-angle-90', 'icofont-angle', 'icofont-calculator-alt-1', 'icofont-circle-ruler-alt', 'icofont-circle-ruler'] },

    { nombre: "Matemáticas 2", items: ['icofont-compass-alt-1', 'icofont-golden-ratio', 'icofont-marker-alt-1', 'icofont-math', 'icofont-mathematical-alt-1', 'icofont-mathematical-alt-2', 'icofont-mathematical', 'icofont-pen-alt-2', 'icofont-ruler-alt-1', 'icofont-pen-holder'] },

    { nombre: "Matemáticas 3", items: ['icofont-superscript', 'icofont-number-exact', 'icofont-numbers', 'icofont-axis', 'icofont-geometry', 'icofont-compass', 'icofont-protractor', 'icofont-ruler-alt-1', 'icofont-ruler-alt-2', 'icofont-pie-chart'] },

        { nombre: "Editor de texto", items: ['icofont-pen-holder-alt-1', 'icofont-pencil-alt-3', 'icofont-ruler-alt-2', 'icofont-ruler-compass-alt', 'icofont-ruler-compass', 'icofont-ruler-pencil-alt-1', 'icofont-ruler-pencil-alt-2', 'icofont-ruler-pencil', 'icofont-ruler', 'icofont-rulers-alt'] },

    { nombre: "Editor de texto 2", items: ['icofont-align-left', 'icofont-align-center', 'icofont-align-right', 'icofont-align-justify', 'icofont-list', 'icofont-numbered-list', 'icofont-outdent', 'icofont-indent', 'icofont-heading', 'icofont-paragraph'] },
    { nombre: "Editor de texto 3", items: ['icofont-link', 'icofont-unlink', 'icofont-cut', 'icofont-copy', 'icofont-paste', 'icofont-save', 'icofont-print', 'icofont-undo', 'icofont-redo', 'icofont-paper-clip'] },
        { nombre: "Aplicación", items: ['icofont-application-alt', 'icofont-ui-calculator', 'icofont-ui-calendar', 'icofont-ui-camera', 'icofont-ui-cart', 'icofont-ui-chat', 'icofont-ui-check', 'icofont-ui-clip', 'icofont-ui-cloud', 'icofont-ui-email'] },
    { nombre: "Aplicación 2", items: ['icofont-ui-file', 'icofont-ui-folder', 'icofont-ui-home', 'icofont-ui-image', 'icofont-ui-lock', 'icofont-ui-map', 'icofont-ui-message', 'icofont-ui-messaging', 'icofont-ui-mic', 'icofont-ui-mms'] },
    { nombre: "Aplicación 3", items: ['icofont-ui-movie', 'icofont-ui-music', 'icofont-ui-note', 'icofont-ui-notification', 'icofont-ui-Password', 'icofont-ui-phone', 'icofont-ui-photo', 'icofont-ui-play', 'icofont-ui-pointer', 'icofont-ui-power'] },
        { nombre: "Duotone", items: ['icofont-duotone-alarm', 'icofont-duotone-ambulance', 'icofont-duotone-anchor', 'icofont-duotone-archive', 'icofont-duotone-atom', 'icofont-duotone-award', 'icofont-duotone-baby', 'icofont-duotone-bag', 'icofont-duotone-balance', 'icofont-duotone-bank'] },
    { nombre: "Duotone 2", items: ['icofont-duotone-bar-code', 'icofont-duotone-basket', 'icofont-duotone-battery', 'icofont-duotone-bed', 'icofont-duotone-bell', 'icofont-duotone-bill', 'icofont-duotone-bird', 'icofont-duotone-book', 'icofont-duotone-bookmark', 'icofont-duotone-bottle'] },
    { nombre: "Duotone 3", items: ['icofont-duotone-box', 'icofont-duotone-briefcase', 'icofont-duotone-brush', 'icofont-duotone-bucket', 'icofont-duotone-bug', 'icofont-duotone-building', 'icofont-duotone-bulb', 'icofont-duotone-bullhorn', 'icofont-duotone-bus', 'icofont-duotone-calculator'] }
];