export const dict = {
    es: {
        btnJugar: "Jugar",
        btnComoJugar: "Cómo Jugar",
        btnAjustes: "Ajustes",
        btnDesarrolladores: "Desarrolladores",
        btnVolver: "Volver",
        iniciarJuego: "Iniciar Juego",
        pausar: "Pausar",
        reanudar: "Reanudar",
        tiempo: "Tiempo",
        puntos: "Puntos",
        victorias: "Victorias",
        record: "Récord",
        score: "Score",
        derrotas: "Derrotas",
        gameOverTitulo: "¡Game Over!",
        gameOverMsg: "¡Lástima! Te has quedado sin vidas.",
        victoriaTitulo: "¡Victoria!",
        victoriaMsg: "¡Felicitaciones, has completado el nivel con éxito!",
        btnSiguiente: "Siguiente Nivel",
        btnReintentar: "Reintentar Nivel",
        btnIrMenu: "Ir al menú"
    },
    en: {
        btnJugar: "Play",
        btnComoJugar: "How to Play",
        btnAjustes: "Settings",
        btnDesarrolladores: "Developers",
        btnVolver: "Back",
        iniciarJuego: "Start Game",
        pause: "Pause",
        resume: "Resume",
        tiempo: "Time",
        puntos: "Score",
        victorias: "Wins",
        record: "Best Time",
        score: "Total Score",
        derrotas: "Losses",
        gameOverTitulo: "Game Over!",
        gameOverMsg: "Too bad! You ran out of lives.",
        victoriaTitulo: "Victory!",
        victoriaMsg: "Congratulations, you successfully completed the level!",
        btnSiguiente: "Next Level",
        btnReintentar: "Retry Level",
        btnIrMenu: "Main Menu"
    },
    pt: {
        btnJugar: "Jogar",
        btnComoJugar: "Como Jogar",
        btnAjustes: "Configurações",
        btnDesarrolladores: "Desenvolvedores",
        btnVolver: "Voltar",
        iniciarJuego: "Iniciar Jogo",
        tiempo: "Tempo",
        puntos: "Pontos",
        victorias: "Vitórias",
        record: "Recorde",
        score: "Pontuação",
        derrotas: "Derrotas",
        gameOverTitulo: "Fim de Jogo!",
        gameOverMsg: "Que pena! Suas vidas acabaram.",
        victoriaTitulo: "Vitória!",
        victoriaMsg: "Parabéns, você concluiu o nível com sucesso!",
        btnSiguiente: "Próximo Nível",
        btnReintentar: "Tentar Novamente",
        btnIrMenu: "Menu Principal"
    }
};